/*Lila Breton, Clarisse Le Page TDC
 *20 novembre 2024
 */
package cpo_lights_off_breton_lepage;

/**
 *
 * @author lilab
 */
public class pageAccueil extends javax.swing.JFrame {

    /**
     * Creates new form pageAccueil
     */
    public pageAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfAccueil = new javax.swing.JPanel();
        Jeu = new javax.swing.JLabel();
        Regles = new javax.swing.JLabel();
        Eteindre = new javax.swing.JLabel();
        AccueilNiveau = new javax.swing.JButton();
        Noms = new javax.swing.JLabel();
        Forme = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 720));
        setPreferredSize(new java.awt.Dimension(800, 720));

        InterfAccueil.setBackground(new java.awt.Color(204, 204, 255));
        InterfAccueil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        InterfAccueil.setPreferredSize(new java.awt.Dimension(614, 418));
        InterfAccueil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jeu.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        Jeu.setText(" Jeu Light Off  ");
        InterfAccueil.add(Jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        Regles.setText("Règles du jeu : ");
        InterfAccueil.add(Regles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Eteindre.setText("Le but du jeu est d'éteindre toutes les lumières (en noir)");
        InterfAccueil.add(Eteindre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 186, -1, -1));

        AccueilNiveau.setText("Continuer");
        AccueilNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilNiveauActionPerformed(evt);
            }
        });
        InterfAccueil.add(AccueilNiveau, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 338, -1, -1));

        Noms.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Noms.setText("Lila, Clarisse TDC");
        InterfAccueil.add(Noms, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 401, 58, -1));

        Forme.setText("Les lumières s'éteignent et s'allument en forme de plus");
        InterfAccueil.add(Forme, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 222, -1, -1));

        jLabel1.setText("Il existe des Jokers sur certains niveaux qui permettent d'éteindre ou d'allumer une seule case");
        InterfAccueil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 258, -1, -1));

        jLabel2.setText("Il vous suffit d'appuyer sur le bouton Joker puis de cliquer sur la case que vous saouhitez éteindre ou allumer");
        InterfAccueil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 287, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(InterfAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(InterfAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccueilNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilNiveauActionPerformed
        PageNiveau Niv = new PageNiveau();
        Niv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccueilNiveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilNiveau;
    private javax.swing.JLabel Eteindre;
    private javax.swing.JLabel Forme;
    private javax.swing.JPanel InterfAccueil;
    private javax.swing.JLabel Jeu;
    private javax.swing.JLabel Noms;
    private javax.swing.JLabel Regles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
