/*Lila Breton, Clarisse Le Page TDC
 *20 novembre 2024
 */
package cpo_lights_off_breton_lepage;

/**
 *
 * @author lilab
 */
public class PageNiveau extends javax.swing.JFrame {

    /**
     * Creates new form PageNiveau
     */
    public PageNiveau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfNiveau = new javax.swing.JPanel();
        Choix = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        NivFacile = new javax.swing.JButton();
        NivInter = new javax.swing.JButton();
        NivDiff = new javax.swing.JButton();
        RegleFac = new javax.swing.JLabel();
        RegleInt = new javax.swing.JLabel();
        RegleDif = new javax.swing.JLabel();
        PhraseIntro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 720));
        setPreferredSize(new java.awt.Dimension(800, 720));

        InterfNiveau.setBackground(new java.awt.Color(204, 255, 204));
        InterfNiveau.setPreferredSize(new java.awt.Dimension(614, 418));
        InterfNiveau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Choix.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Choix.setText("Choix Niveau");
        InterfNiveau.add(Choix, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        InterfNiveau.add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 380, -1, -1));

        NivFacile.setText("Niveau Facile");
        NivFacile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivFacileActionPerformed(evt);
            }
        });
        InterfNiveau.add(NivFacile, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 125, 150, -1));

        NivInter.setText("Niveau Intermédiaire");
        NivInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivInterActionPerformed(evt);
            }
        });
        InterfNiveau.add(NivInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 204, 150, -1));

        NivDiff.setText("Niveau Difficile");
        NivDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NivDiffActionPerformed(evt);
            }
        });
        InterfNiveau.add(NivDiff, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 279, 150, -1));

        RegleFac.setText("Grille 4x4, vous avez 10 coups et 2 Joker");
        InterfNiveau.add(RegleFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 168, -1, -1));

        RegleInt.setText("Grille 7x7, vous avez 15 coups et 1 Joker");
        InterfNiveau.add(RegleInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 245, -1, -1));

        RegleDif.setText("Grille 10x10, vous avez 20 coups et pas de Joker");
        InterfNiveau.add(RegleDif, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 320, -1, -1));

        PhraseIntro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PhraseIntro.setText("Veuillez choisir le niveau de difficulté que vous préfèrez :");
        InterfNiveau.add(PhraseIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 85, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(InterfNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(InterfNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        pageAccueil Retour = new pageAccueil();
        Retour.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RetourActionPerformed

    private void NivFacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivFacileActionPerformed
        FenetrePrincipale Facile = new FenetrePrincipale(4,4,10,10,2);
        Facile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NivFacileActionPerformed

    private void NivInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivInterActionPerformed
        FenetrePrincipale Facile = new FenetrePrincipale(7,7,15,15,1);
        Facile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NivInterActionPerformed

    private void NivDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NivDiffActionPerformed
        FenetrePrincipale Facile = new FenetrePrincipale(10,10,20,20,0);
        Facile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NivDiffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageNiveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageNiveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageNiveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageNiveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageNiveau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Choix;
    private javax.swing.JPanel InterfNiveau;
    private javax.swing.JButton NivDiff;
    private javax.swing.JButton NivFacile;
    private javax.swing.JButton NivInter;
    private javax.swing.JLabel PhraseIntro;
    private javax.swing.JLabel RegleDif;
    private javax.swing.JLabel RegleFac;
    private javax.swing.JLabel RegleInt;
    private javax.swing.JButton Retour;
    // End of variables declaration//GEN-END:variables
}
