/*Lila Breton, Clarisse Le Page TDC
 *20 novembre 2024
 */
package cpo_lights_off_breton_lepage;

/**
 *
 * @author lilab
 */
public class pageAccueil extends javax.swing.JFrame {

    /**
     * Creates new form pageAccueil
     */
    public pageAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfAccueil = new javax.swing.JPanel();
        Jeu = new javax.swing.JLabel();
        Regles = new javax.swing.JLabel();
        Eteindre = new javax.swing.JLabel();
        AccueilNiveau = new javax.swing.JButton();
        Noms = new javax.swing.JLabel();
        Forme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1540, 820));

        InterfAccueil.setBackground(new java.awt.Color(204, 204, 255));

        Jeu.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        Jeu.setText(" Jeu Light Off  ");

        Regles.setText("Règles du jeu : ");

        Eteindre.setText("Le but du jeu est d'éteindre toutes les lumières (en noir)");

        AccueilNiveau.setText("Continuer");
        AccueilNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccueilNiveauActionPerformed(evt);
            }
        });

        Noms.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Noms.setText("Lila, Clarisse TDC");

        Forme.setText("Les lumières s'éteignent et s'allument en forme de plus");

        javax.swing.GroupLayout InterfAccueilLayout = new javax.swing.GroupLayout(InterfAccueil);
        InterfAccueil.setLayout(InterfAccueilLayout);
        InterfAccueilLayout.setHorizontalGroup(
            InterfAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfAccueilLayout.createSequentialGroup()
                .addGroup(InterfAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterfAccueilLayout.createSequentialGroup()
                        .addGroup(InterfAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InterfAccueilLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(Regles))
                            .addGroup(InterfAccueilLayout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(AccueilNiveau)))
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterfAccueilLayout.createSequentialGroup()
                        .addGap(548, 548, 548)
                        .addComponent(Noms, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(InterfAccueilLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(InterfAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jeu)
                    .addComponent(Eteindre)
                    .addComponent(Forme))
                .addGap(150, 150, 150))
        );
        InterfAccueilLayout.setVerticalGroup(
            InterfAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfAccueilLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Jeu)
                .addGap(50, 50, 50)
                .addComponent(Regles)
                .addGap(20, 20, 20)
                .addComponent(Eteindre)
                .addGap(20, 20, 20)
                .addComponent(Forme)
                .addGap(60, 60, 60)
                .addComponent(AccueilNiveau)
                .addGap(80, 80, 80)
                .addComponent(Noms)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(InterfAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(InterfAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccueilNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccueilNiveauActionPerformed
        PageNiveau Niv = new PageNiveau();
        Niv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccueilNiveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccueilNiveau;
    private javax.swing.JLabel Eteindre;
    private javax.swing.JLabel Forme;
    private javax.swing.JPanel InterfAccueil;
    private javax.swing.JLabel Jeu;
    private javax.swing.JLabel Noms;
    private javax.swing.JLabel Regles;
    // End of variables declaration//GEN-END:variables
}
